version: '3'
services:
  node1:
    build: .
    hostname: node1
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=R00tVe3etable
      - REPLICATION_PASSWORD=Sw33tPotat0
      - NODE_NAME=node1
      - CLUSTER_ADDRESS=gcomm://node1,node2,node3
      - OTHER_NODES=node2 node3
      - PRIMARY=node1
      - NODE_COUNT=3
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - RECOVER=false
    volumes:
      - node1-mysql:/var/lib/mysql
      - node1-interlock:/interlock
  
  node2:
    build: .
    hostname: node2
    links:
     - node1
    depends_on:
      - node1
    ports:
      - 23306:3306
    environment:
      - REPLICATION_PASSWORD=Sw33tPotat0
      - NODE_NAME=node2
      - CLUSTER_ADDRESS=gcomm://node1,node2,node3
      - PRIMARY=node1
      - NODE_COUNT=3
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - RECOVER=false
    volumes:
      - node2-mysql:/var/lib/mysql
      - node2-interlock:/interlock
  
  node3:
    build: .
    hostname: node3
    depends_on:
      - node1
      - node2
    links:
      - node1
    ports:
      - 33306:3306
    environment:
      - REPLICATION_PASSWORD=Sw33tPotat0
      - NODE_NAME=node3
      - CLUSTER_ADDRESS=gcomm://node1,node2,node3
      - PRIMARY=node1
      - NODE_COUNT=3
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - RECOVER=false
    volumes:
      - node3-mysql:/var/lib/mysql
      - node3-interlock:/interlock
volumes:
  node1-mysql: {}
  node2-mysql: {}
  node3-mysql: {}
  node1-interlock: {}
  node2-interlock: {}
  node3-interlock: {}
