#!/bin/bash

parse_args() {
  POSITIONAL=()
  while [[ $# -gt 0 ]]
  do
    key="$1"
    case "$key" in
        -q)
                QUIET=yes
                shift
                ;;
        -b)
                REBUILD=yes
                shift
                ;;
        -s)
                RESTART=yes
                shift
                ;;
         *)
         		shift
         		;;
    esac
  done
  set -- "${POSITIONAL[@]}"
}

parse_args $*

#
# Use APACHE_FQDN to set up the ACS URL(s)
#
export pemstr=`cat ../apache-sp/sp-cert.pem | grep -v '^-' | sed 's/\w//g'`
cat config/shib-idp/metadata/local-sites.xml.tmpl | sed 's/%apache_fqdn%/'$APACHE_FQDN'/g' | perl -e 'while (<STDIN>) { $_ =~ s/%car-demo-sp-certificate%/$ENV{"pemstr"}/; print }' > config/shib-idp/metadata/local-sites.xml
cp config/shib-idp/metadata/idp-metadata.xml wwwroot/

