version: '3'
services:
  buildnode:
    build: .
    hostname: buildnode
    volumes:
      - $thisdir/../../arpsi:/var/build/arpsi
      - $thisdir/../../copsu:/var/build/copsu
      - $thisdir/../../car:/var/build/car
      - $thisdir/../../caradmin:/var/build/caradmin
      - $thisdir/../../icm:/var/build/icm
      - $thisdir/../../informed:/var/build/informed
      - $thisdir/../../regloader:/var/build/regloader
      - arpsi-webapps:/var/lib/arpsi/webapps
      - copsu-webapps:/var/lib/copsu/webapps
      - car-webapps:/var/lib/car/webapps
      - caradmin-webapps:/var/lib/caradmin/webapps
      - icm-webapps:/var/lib/icm/webapps
      - informed-webapps:/var/lib/informed/webapps
      - regloader-webapps:/var/lib/regloader/webapps
      - ldap-container:/var/lib/ldap/container
      - ldap-data:/var/lib/ldap/data
volumes:
  arpsi-webapps: {}
  copsu-webapps: {}
  car-webapps: {}
  caradmin-webapps: {}
  icm-webapps: {}
  informed-webapps: {}
  regloader-webapps: {}
  ldap-container: {}
  ldap-data: {}
  

